<?php

return [
    'formatting' => [
        'decimals' => 2,
        'format_values' => false,
        'decimal_separator' => '.',
        'thousands_separator' => ',',
    ],

    'currencies' => [
        'default' => 'ZAR',

        'collection' => [
            [
                'name' => 'US Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Canadian Dollar',
                'code' => 'CAD',
                'symbol' => 'CA$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'symbol_native' => '€',
            ],
            [
                'name' => 'United Arab Emirates Dirham',
                'code' => 'AED',
                'symbol' => 'AED',
                'symbol_native' => 'د.إ.‏',
            ],
            [
                'name' => 'Afghan Afghani',
                'code' => 'AFN',
                'symbol' => 'Af',
                'symbol_native' => '؋',
            ],
            [
                'name' => 'Albanian Lek',
                'code' => 'ALL',
                'symbol' => 'ALL',
                'symbol_native' => 'Lek',
            ],
            [
                'name' => 'Armenian Dram',
                'code' => 'AMD',
                'symbol' => 'AMD',
                'symbol_native' => 'դր.',
            ],
            [
                'name' => 'Argentine Peso',
                'code' => 'ARS',
                'symbol' => 'AR$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => 'AU$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Azerbaijani Manat',
                'code' => 'AZN',
                'symbol' => 'man.',
                'symbol_native' => 'ман.',
            ],
            [
                'name' => 'Bosnia-Herzegovina Convertible Mark',
                'code' => 'BAM',
                'symbol' => 'KM',
                'symbol_native' => 'KM',
            ],
            [
                'name' => 'Bangladeshi Taka',
                'code' => 'BDT',
                'symbol' => 'Tk',
                'symbol_native' => '৳',
            ],
            [
                'name' => 'Bulgarian Lev',
                'code' => 'BGN',
                'symbol' => 'BGN',
                'symbol_native' => 'лв.',
            ],
            [
                'name' => 'Bahraini Dinar',
                'code' => 'BHD',
                'symbol' => 'BD',
                'symbol_native' => 'د.ب.‏',
            ],
            [
                'name' => 'Burundian Franc',
                'code' => 'BIF',
                'symbol' => 'FBu',
                'symbol_native' => 'FBu',
            ],
            [
                'name' => 'Brunei Dollar',
                'code' => 'BND',
                'symbol' => 'BN$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Bolivian Boliviano',
                'code' => 'BOB',
                'symbol' => 'Bs',
                'symbol_native' => 'Bs',
            ],
            [
                'name' => 'Brazilian Real',
                'code' => 'BRL',
                'symbol' => 'R$',
                'symbol_native' => 'R$',
            ],
            [
                'name' => 'Botswanan Pula',
                'code' => 'BWP',
                'symbol' => 'BWP',
                'symbol_native' => 'P',
            ],
            [
                'name' => 'Belarusian Ruble',
                'code' => 'BYN',
                'symbol' => 'Br',
                'symbol_native' => 'руб.',
            ],
            [
                'name' => 'Belize Dollar',
                'code' => 'BZD',
                'symbol' => 'BZ$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Congolese Franc',
                'code' => 'CDF',
                'symbol' => 'CDF',
                'symbol_native' => 'FrCD',
            ],
            [
                'name' => 'Swiss Franc',
                'code' => 'CHF',
                'symbol' => 'CHF',
                'symbol_native' => 'CHF',
            ],
            [
                'name' => 'Chilean Peso',
                'code' => 'CLP',
                'symbol' => 'CL$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Chinese Yuan',
                'code' => 'CNY',
                'symbol' => 'CN¥',
                'symbol_native' => 'CN¥',
            ],
            [
                'name' => 'Colombian Peso',
                'code' => 'COP',
                'symbol' => 'CO$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Costa Rican Colón',
                'code' => 'CRC',
                'symbol' => '₡',
                'symbol_native' => '₡',
            ],
            [
                'name' => 'Cape Verdean Escudo',
                'code' => 'CVE',
                'symbol' => 'CV$',
                'symbol_native' => 'CV$',
            ],
            [
                'name' => 'Czech Republic Koruna',
                'code' => 'CZK',
                'symbol' => 'Kč',
                'symbol_native' => 'Kč',
            ],
            [
                'name' => 'Djiboutian Franc',
                'code' => 'DJF',
                'symbol' => 'Fdj',
                'symbol_native' => 'Fdj',
            ],
            [
                'name' => 'Danish Krone',
                'code' => 'DKK',
                'symbol' => 'Dkr',
                'symbol_native' => 'kr',
            ],
            [
                'name' => 'Dominican Peso',
                'code' => 'DOP',
                'symbol' => 'RD$',
                'symbol_native' => 'RD$',
            ],
            [
                'name' => 'Algerian Dinar',
                'code' => 'DZD',
                'symbol' => 'DA',
                'symbol_native' => 'د.ج.‏',
            ],
            [
                'name' => 'Estonian Kroon',
                'code' => 'EEK',
                'symbol' => 'Ekr',
                'symbol_native' => 'kr',
            ],
            [
                'name' => 'Egyptian Pound',
                'code' => 'EGP',
                'symbol' => 'EGP',
                'symbol_native' => 'ج.م.‏',
            ],
            [
                'name' => 'Eritrean Nakfa',
                'code' => 'ERN',
                'symbol' => 'Nfk',
                'symbol_native' => 'Nfk',
            ],
            [
                'name' => 'Ethiopian Birr',
                'code' => 'ETB',
                'symbol' => 'Br',
                'symbol_native' => 'Br',
            ],
            [
                'name' => 'British Pound Sterling',
                'code' => 'GBP',
                'symbol' => '£',
                'symbol_native' => '£',
            ],
            [
                'name' => 'Georgian Lari',
                'code' => 'GEL',
                'symbol' => 'GEL',
                'symbol_native' => 'GEL',
            ],
            [
                'name' => 'Ghanaian Cedi',
                'code' => 'GHS',
                'symbol' => 'GH₵',
                'symbol_native' => 'GH₵',
            ],
            [
                'name' => 'Guinean Franc',
                'code' => 'GNF',
                'symbol' => 'FG',
                'symbol_native' => 'FG',
            ],
            [
                'name' => 'Guatemalan Quetzal',
                'code' => 'GTQ',
                'symbol' => 'GTQ',
                'symbol_native' => 'Q',
            ],
            [
                'name' => 'Hong Kong Dollar',
                'code' => 'HKD',
                'symbol' => 'HK$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Honduran Lempira',
                'code' => 'HNL',
                'symbol' => 'HNL',
                'symbol_native' => 'L',
            ],
            [
                'name' => 'Croatian Kuna',
                'code' => 'HRK',
                'symbol' => 'kn',
                'symbol_native' => 'kn',
            ],
            [
                'name' => 'Hungarian Forint',
                'code' => 'HUF',
                'symbol' => 'Ft',
                'symbol_native' => 'Ft',
            ],
            [
                'name' => 'Indonesian Rupiah',
                'code' => 'IDR',
                'symbol' => 'Rp',
                'symbol_native' => 'Rp',
            ],
            [
                'name' => 'Israeli New Sheqel',
                'code' => 'ILS',
                'symbol' => '₪',
                'symbol_native' => '₪',
            ],
            [
                'name' => 'Indian Rupee',
                'code' => 'INR',
                'symbol' => 'Rs',
                'symbol_native' => 'টকা',
            ],
            [
                'name' => 'Iraqi Dinar',
                'code' => 'IQD',
                'symbol' => 'IQD',
                'symbol_native' => 'د.ع.‏',
            ],
            [
                'name' => 'Iranian Rial',
                'code' => 'IRR',
                'symbol' => 'IRR',
                'symbol_native' => '﷼',
            ],
            [
                'name' => 'Icelandic Króna',
                'code' => 'ISK',
                'symbol' => 'Ikr',
                'symbol_native' => 'kr',
            ],
            [
                'name' => 'Jamaican Dollar',
                'code' => 'JMD',
                'symbol' => 'J$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Jordanian Dinar',
                'code' => 'JOD',
                'symbol' => 'JD',
                'symbol_native' => 'د.أ.‏',
            ],
            [
                'name' => 'Japanese Yen',
                'code' => 'JPY',
                'symbol' => '¥',
                'symbol_native' => '￥',
            ],
            [
                'name' => 'Kenyan Shilling',
                'code' => 'KES',
                'symbol' => 'Ksh',
                'symbol_native' => 'Ksh',
            ],
            [
                'name' => 'Cambodian Riel',
                'code' => 'KHR',
                'symbol' => 'KHR',
                'symbol_native' => '៛',
            ],
            [
                'name' => 'Comorian Franc',
                'code' => 'KMF',
                'symbol' => 'CF',
                'symbol_native' => 'FC',
            ],
            [
                'name' => 'South Korean Won',
                'code' => 'KRW',
                'symbol' => '₩',
                'symbol_native' => '₩',
            ],
            [
                'name' => 'Kuwaiti Dinar',
                'code' => 'KWD',
                'symbol' => 'KD',
                'symbol_native' => 'د.ك.‏',
            ],
            [
                'name' => 'Kazakhstani Tenge',
                'code' => 'KZT',
                'symbol' => 'KZT',
                'symbol_native' => 'тңг.',
            ],
            [
                'name' => 'Lebanese Pound',
                'code' => 'LBP',
                'symbol' => 'LB£',
                'symbol_native' => 'ل.ل.‏',
            ],
            [
                'name' => 'Sri Lankan Rupee',
                'code' => 'LKR',
                'symbol' => 'SLRs',
                'symbol_native' => 'SL Re',
            ],
            [
                'name' => 'Lithuanian Litas',
                'code' => 'LTL',
                'symbol' => 'Lt',
                'symbol_native' => 'Lt',
            ],
            [
                'name' => 'Latvian Lats',
                'code' => 'LVL',
                'symbol' => 'Ls',
                'symbol_native' => 'Ls',
            ],
            [
                'name' => 'Libyan Dinar',
                'code' => 'LYD',
                'symbol' => 'LD',
                'symbol_native' => 'د.ل.‏',
            ],
            [
                'name' => 'Moroccan Dirham',
                'code' => 'MAD',
                'symbol' => 'MAD',
                'symbol_native' => 'د.م.‏',
            ],
            [
                'name' => 'Moldovan Leu',
                'code' => 'MDL',
                'symbol' => 'MDL',
                'symbol_native' => 'MDL',
            ],
            [
                'name' => 'Malagasy Ariary',
                'code' => 'MGA',
                'symbol' => 'MGA',
                'symbol_native' => 'MGA',
            ],
            [
                'name' => 'Macedonian Denar',
                'code' => 'MKD',
                'symbol' => 'MKD',
                'symbol_native' => 'MKD',
            ],
            [
                'name' => 'Myanma Kyat',
                'code' => 'MMK',
                'symbol' => 'MMK',
                'symbol_native' => 'K',
            ],
            [
                'name' => 'Macanese Pataca',
                'code' => 'MOP',
                'symbol' => 'MOP$',
                'symbol_native' => 'MOP$',
            ],
            [
                'name' => 'Mauritian Rupee',
                'code' => 'MUR',
                'symbol' => 'MURs',
                'symbol_native' => 'MURs',
            ],
            [
                'name' => 'Mexican Peso',
                'code' => 'MXN',
                'symbol' => 'MX$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Malaysian Ringgit',
                'code' => 'MYR',
                'symbol' => 'RM',
                'symbol_native' => 'RM',
            ],
            [
                'name' => 'Mozambican Metical',
                'code' => 'MZN',
                'symbol' => 'MTn',
                'symbol_native' => 'MTn',
            ],
            [
                'name' => 'Namibian Dollar',
                'code' => 'NAD',
                'symbol' => 'N$',
                'symbol_native' => 'N$',
            ],
            [
                'name' => 'Nigerian Naira',
                'code' => 'NGN',
                'symbol' => '₦',
                'symbol_native' => '₦',
            ],
            [
                'name' => 'Nicaraguan Córdoba',
                'code' => 'NIO',
                'symbol' => 'C$',
                'symbol_native' => 'C$',
            ],
            [
                'name' => 'Norwegian Krone',
                'code' => 'NOK',
                'symbol' => 'Nkr',
                'symbol_native' => 'kr',
            ],
            [
                'name' => 'Nepalese Rupee',
                'code' => 'NPR',
                'symbol' => 'NPRs',
                'symbol_native' => 'नेरू',
            ],
            [
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => 'NZ$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Omani Rial',
                'code' => 'OMR',
                'symbol' => 'OMR',
                'symbol_native' => 'ر.ع.‏',
            ],
            [
                'name' => 'Panamanian Balboa',
                'code' => 'PAB',
                'symbol' => 'B/.',
                'symbol_native' => 'B/.',
            ],
            [
                'name' => 'Peruvian Nuevo Sol',
                'code' => 'PEN',
                'symbol' => 'S/.',
                'symbol_native' => 'S/.',
            ],
            [
                'name' => 'Philippine Peso',
                'code' => 'PHP',
                'symbol' => '₱',
                'symbol_native' => '₱',
            ],
            [
                'name' => 'Pakistani Rupee',
                'code' => 'PKR',
                'symbol' => 'PKRs',
                'symbol_native' => '₨',
            ],
            [
                'name' => 'Polish Zloty',
                'code' => 'PLN',
                'symbol' => 'zł',
                'symbol_native' => 'zł',
            ],
            [
                'name' => 'Paraguayan Guarani',
                'code' => 'PYG',
                'symbol' => '₲',
                'symbol_native' => '₲',
            ],
            [
                'name' => 'Qatari Rial',
                'code' => 'QAR',
                'symbol' => 'QR',
                'symbol_native' => 'ر.ق.‏',
            ],
            [
                'name' => 'Romanian Leu',
                'code' => 'RON',
                'symbol' => 'RON',
                'symbol_native' => 'RON',
            ],
            [
                'name' => 'Serbian Dinar',
                'code' => 'RSD',
                'symbol' => 'din.',
                'symbol_native' => 'дин.',
            ],
            [
                'name' => 'Russian Ruble',
                'code' => 'RUB',
                'symbol' => 'RUB',
                'symbol_native' => '₽.',
            ],
            [
                'name' => 'Rwandan Franc',
                'code' => 'RWF',
                'symbol' => 'RWF',
                'symbol_native' => 'FR',
            ],
            [
                'name' => 'Saudi Riyal',
                'code' => 'SAR',
                'symbol' => 'SR',
                'symbol_native' => 'ر.س.‏',
            ],
            [
                'name' => 'Sudanese Pound',
                'code' => 'SDG',
                'symbol' => 'SDG',
                'symbol_native' => 'SDG',
            ],
            [
                'name' => 'Swedish Krona',
                'code' => 'SEK',
                'symbol' => 'Skr',
                'symbol_native' => 'kr',
            ],
            [
                'name' => 'Singapore Dollar',
                'code' => 'SGD',
                'symbol' => 'S$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Somali Shilling',
                'code' => 'SOS',
                'symbol' => 'Ssh',
                'symbol_native' => 'Ssh',
            ],
            [
                'name' => 'Syrian Pound',
                'code' => 'SYP',
                'symbol' => 'SY£',
                'symbol_native' => 'ل.س.‏',
            ],
            [
                'name' => 'Thai Baht',
                'code' => 'THB',
                'symbol' => '฿',
                'symbol_native' => '฿',
            ],
            [
                'name' => 'Tunisian Dinar',
                'code' => 'TND',
                'symbol' => 'DT',
                'symbol_native' => 'د.ت.‏',
            ],
            [
                'name' => 'Tongan Paʻanga',
                'code' => 'TOP',
                'symbol' => 'T$',
                'symbol_native' => 'T$',
            ],
            [
                'name' => 'Turkish Lira',
                'code' => 'TRY',
                'symbol' => 'TL',
                'symbol_native' => 'TL',
            ],
            [
                'name' => 'Trinidad and Tobago Dollar',
                'code' => 'TTD',
                'symbol' => 'TT$',
                'symbol_native' => '$',
            ],
            [
                'name' => 'New Taiwan Dollar',
                'code' => 'TWD',
                'symbol' => 'NT$',
                'symbol_native' => 'NT$',
            ],
            [
                'name' => 'Tanzanian Shilling',
                'code' => 'TZS',
                'symbol' => 'TSh',
                'symbol_native' => 'TSh',
            ],
            [
                'name' => 'Ukrainian Hryvnia',
                'code' => 'UAH',
                'symbol' => '₴',
                'symbol_native' => '₴',
            ],
            [
                'name' => 'Ugandan Shilling',
                'code' => 'UGX',
                'symbol' => 'USh',
                'symbol_native' => 'USh',
            ],
            [
                'name' => 'Uruguayan Peso',
                'code' => 'UYU',
                'symbol' => '$U',
                'symbol_native' => '$',
            ],
            [
                'name' => 'Uzbekistan Som',
                'code' => 'UZS',
                'symbol' => 'UZS',
                'symbol_native' => 'UZS',
            ],
            [
                'name' => 'Venezuelan Bolívar',
                'code' => 'VEF',
                'symbol' => 'Bs.F.',
                'symbol_native' => 'Bs.F.',
            ],
            [
                'name' => 'Vietnamese Dong',
                'code' => 'VND',
                'symbol' => '₫',
                'symbol_native' => '₫',
            ],
            [
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'symbol' => 'FCFA',
                'symbol_native' => 'FCFA',
            ],
            [
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'symbol' => 'CFA',
                'symbol_native' => 'CFA',
            ],
            [
                'name' => 'Yemeni Rial',
                'code' => 'YER',
                'symbol' => 'YR',
                'symbol_native' => 'ر.ي.‏',
            ],
            [
                'name' => 'South African Rand',
                'code' => 'ZAR',
                'symbol' => 'R',
                'symbol_native' => 'R',
            ],
            [
                'name' => 'Zambian Kwacha',
                'code' => 'ZMK',
                'symbol' => 'ZK',
                'symbol_native' => 'ZK',
            ],
            [
                'name' => 'Zimbabwean Dollar',
                'code' => 'ZWL',
                'symbol' => 'ZWL$',
                'symbol_native' => 'ZWL$',
            ],
        ],
    ],
];
